#!/bin/bash

text=$(tee | sed 's/\x00//g' | sed -E 's/^~[^>]+>//' | sed -E 's/(took |at |ranger ).*$//' | sed -E 's/^[-dl][rwx].+([0-9]{2}:[0-9]{2}|[0-9]{1,2}日)//' | sed -E 's/(^\s+|\s+$)//g' | sed '/^\s*$/d' | awk -F '[[:space:]]+' '{ for (i=1; i<=NF; i++) { if ($i != "") print $i; } if ($0 != "") print $0 }' | awk -F '(/|;|:)' '{ for (i=1; i<=NF; i++) { if ($i != "") print $i; } if ($0 != "") print $0 }' | awk -F '\.' '{ for (i=1; i<=NF; i++) { if ($i != "") print $i; } if ($0 != "") print $0 }' | sort | uniq | awk '{ print length, $0 }' | sort -n | cut -d' ' -f2-)
echo -n "$text" | rofi-paste -s '\n' -p 'Copy which segment?'
